import { describe, it, expect } from 'vitest';
import { countGeneratedFiles, filterGeneratedFiles } from './generated-files';
import { createMockFile, createMockDir } from './test-fixtures';

describe('countGeneratedFiles', () => {
  it('returns 0 for a tree with no files', () => {
    const tree = createMockDir('root');
    expect(countGeneratedFiles(tree)).toBe(0);
  });

  it('returns 0 when no files are generated', () => {
    const tree = createMockDir('root', [
      createMockFile({ name: 'index.ts', path: '/index.ts' }),
      createMockFile({ name: 'utils.ts', path: '/utils.ts' }),
    ]);
    expect(countGeneratedFiles(tree)).toBe(0);
  });

  it('counts generated files at the root level', () => {
    const tree = createMockDir('root', [
      createMockFile({ name: 'index.ts', path: '/index.ts', isGenerated: false }),
      createMockFile({ name: 'bundle.js', path: '/bundle.js', isGenerated: true }),
    ]);
    expect(countGeneratedFiles(tree)).toBe(1);
  });

  it('counts generated files recursively across nested directories', () => {
    const tree = createMockDir('root', [
      createMockFile({ name: 'normal.ts', path: '/normal.ts', isGenerated: false }),
      createMockDir('dist', [
        createMockFile({ name: 'bundle.js', path: '/dist/bundle.js', isGenerated: true }),
        createMockFile({ name: 'bundle.js.map', path: '/dist/bundle.js.map', isGenerated: true }),
      ]),
      createMockDir('src', [
        createMockFile({ name: 'main.ts', path: '/src/main.ts' }),
        createMockDir('generated', [
          createMockFile({ name: 'proto.ts', path: '/src/generated/proto.ts', isGenerated: true }),
        ]),
      ]),
    ]);
    expect(countGeneratedFiles(tree)).toBe(3);
  });

  it('treats files without isGenerated as not generated', () => {
    // createMockFile does not set isGenerated by default (it's undefined)
    const tree = createMockDir('root', [
      createMockFile({ name: 'index.ts', path: '/index.ts' }),
    ]);
    expect(countGeneratedFiles(tree)).toBe(0);
  });
});

describe('filterGeneratedFiles', () => {
  it('returns an identical structure when no files are generated', () => {
    const file = createMockFile({ name: 'index.ts', path: '/index.ts' });
    const tree = createMockDir('root', [file]);
    const result = filterGeneratedFiles(tree);
    expect(result.children).toHaveLength(1);
    expect(result.children[0]).toBe(file);
  });

  it('removes generated files from the root directory', () => {
    const tree = createMockDir('root', [
      createMockFile({ name: 'index.ts', path: '/index.ts' }),
      createMockFile({ name: 'bundle.js', path: '/bundle.js', isGenerated: true }),
    ]);
    const result = filterGeneratedFiles(tree);
    expect(result.children).toHaveLength(1);
    expect(result.children[0]).toMatchObject({ name: 'index.ts' });
  });

  it('removes generated files from nested directories', () => {
    const tree = createMockDir('root', [
      createMockDir('dist', [
        createMockFile({ name: 'bundle.js', path: '/dist/bundle.js', isGenerated: true }),
        createMockFile({ name: 'bundle.js.map', path: '/dist/bundle.js.map', isGenerated: true }),
      ]),
      createMockDir('src', [
        createMockFile({ name: 'main.ts', path: '/src/main.ts' }),
      ]),
    ]);
    const result = filterGeneratedFiles(tree);
    // 'dist' directory becomes empty and should be removed
    expect(result.children).toHaveLength(1);
    expect(result.children[0]).toMatchObject({ name: 'src' });
  });

  it('removes empty directories after filtering', () => {
    const tree = createMockDir('root', [
      createMockDir('generated', [
        createMockFile({ name: 'proto.ts', path: '/generated/proto.ts', isGenerated: true }),
      ]),
      createMockFile({ name: 'index.ts', path: '/index.ts' }),
    ]);
    const result = filterGeneratedFiles(tree);
    expect(result.children).toHaveLength(1);
    expect(result.children[0]).toMatchObject({ name: 'index.ts' });
  });

  it('does not mutate the original tree', () => {
    const generatedFile = createMockFile({ name: 'bundle.js', path: '/bundle.js', isGenerated: true });
    const normalFile = createMockFile({ name: 'index.ts', path: '/index.ts' });
    const tree = createMockDir('root', [normalFile, generatedFile]);

    filterGeneratedFiles(tree);

    // Original tree must remain unchanged
    expect(tree.children).toHaveLength(2);
  });

  it('returns the root DirectoryNode with empty children when all children are filtered out', () => {
    const tree = createMockDir('root', [
      createMockFile({ name: 'bundle.js', path: '/bundle.js', isGenerated: true }),
    ]);
    // The root is always preserved so callers always receive a valid DirectoryNode.
    const result = filterGeneratedFiles(tree);
    expect(result).toBeDefined();
    expect(result.type).toBe('directory');
    expect(result.children).toHaveLength(0);
  });
});
